FROM public.ecr.aws/lambda/python:3.11

# Set the working directory 
WORKDIR ${LAMBDA_TASK_ROOT}

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy over email files
COPY report.py .

# Set the CMD to the handler file and function
CMD ["report.handler"] 