FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY extract_jd.py .

COPY transform_jd.py .

COPY load_jd.py .

CMD [ "load_jd.handler" ]