FROM python:latest

EXPOSE 8501

WORKDIR /dashboard

COPY requirements.txt .

RUN pip install -r requirements.txt 

RUN mkdir pages
COPY pages/home_page.py pages
COPY pages/track_new_product.py pages

COPY login.py .
COPY functions_dashboard.py .

CMD ["streamlit", "run", "login.py", "--server.port=8501", "--server.address=0.0.0.0"]