FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY extract_steam.py .

COPY transform_steam.py .

COPY load_steam.py .

CMD [ "load.handler" ]