name: Pylint and Pytest Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        find . -type f -name "requirements.txt" | sed -e 's/^/-r /' | xargs pip install
        pip install pylint

    - name: Run pylint
      run: |
        pylint --fail-under=8.5 *.py 

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install requirements.txt and pytest
      run: |
        find . -type f -name "requirements.txt" | sed -e 's/^/-r /' | xargs pip install
        pip install pytest
    - name: Run tests
      run: |
        pytest *.py
    
    - name: Run pytest coverage
      run: |
        pytest --cov-fail-under=60