name: Pylint and Pytest Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install requirements and pylint
      run: |
        pip install pylint
        find . -type f -name "requirements.txt" | sed -e 's/^/-r /' | xargs pip install
    - name: Run pylint
      run: |
        find . -type f -name "*.py" -maxdepth 2 | xargs pylint --disable=I1101 --fail-under=9
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install requirements.txt and pytest
      run: |
        pip install pytest
        find . -type f -name "requirements.txt" | sed -e 's/^/-r /' | xargs pip install
    - name: Run tests
      run: |
        pytest